version: "3.8"

name: quark

services:
  server:
    container_name: quark_server
    build:
      context: ./server
      dockerfile: dev.dockerfile
    volumes:
      - ./server:/usr/src/app
    ports:
      - "8080:8080"
  client:
    container_name: quark_client
    build:
      context: ./client
      dockerfile: dev.dockerfile
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
