version: "3"

env:
  BINARY_NAME: "quark_server"
  BUILD_DIR: "build"
  SRC_DIR: "base_src_server"

tasks:
  dev:
    - air -c .air.toml
  air:
    - go build -o ./tmp/main .
  build:
    - mkdir -p $BUILD_DIR
    - go build -o $BUILD_DIR/$BINARY_NAME .
  clean:
    - rm -rf $BUILD_DIR
    - rm -rf $SRC_DIR
