// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.648
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Navbar() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"sticky top-0 left-0 right-0 py-2 px-3 flex items-center justify-between\"><div class=\"flex items-center justify-between w-full bg-base-300 rounded-xl p-4\"><div class=\"flex items-center gap-[20px]\"><a hx-boost=\"true\" class=\"text-xl link\" href=\"/\">Home</a> <a hx-boost=\"true\" class=\"text-xl link\" href=\"/login\">Login</a> <a hx-boost=\"true\" class=\"text-xl link\" href=\"/register\">Register</a> <a hx-boost=\"true\" class=\"text-xl link\" href=\"/chat\">Chat</a></div><button class=\"btn\" hx-swap=\"none\" hx-get=\"/auth/logout\">Logout</button></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
